apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-container
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: example-container
